[package]
name = "doqplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

trust-dns-resolver = { version = "0.22", features = ["dns-over-quic"] }

rustls = "0.20"
webpki-roots = "^0.23"
